<?php

$config['COURSES_NOT_AVAILABLE'] = array(
    '2012' => array(
        'Winter' => array(
            array('SOEN', '423'),
            array('COMP', '478'),
            array('COMP', '451'),
            array('MECH', '482'),
            array('MECH', '480'),
            array('SOEN', '423'),
            array('SOEN', '422'),
            array('COEN', '320'),
            array('COEN', '317'),
            array('SOEN', '387'),
            array('COMP', '479'),
            array('COMP', '376'),
            array('PHIL', '330'),
            array('PHIL', '275'),
            array('PHIL', '233'),
            array('HIST', '281'),
            array('HIST', '201'),
            array('FMST', '214'),
            array('FLIT', '230'),
            array('ARTH', '354'),
            array('SCPA', '215'),
            array('RELI', '310'),
            array('POLI', '213'),
            array('LING', '300'),
            array('PHYS', '334'),
            array('PHYS', '253'),
            array('GEOL', '208'),
            array('GEOL', '206'),
            array('CHEM', '217'),
            array('SOEN', '448'),
            array('SOEN', '431'),
            array('COMP', '444'),
            array('SOEN', '321'),
            array('MANA', '266'),
            array('MANA', '213'),
            array('LBCL', '204'),
            array('LBCL', '203'),
            array('LBCL', '202'),
            array('LBCL', '201'),
            array('HIST', '283'),
            array('RELI', '374'),
            array('RELI', '218'),
            array('POLI', '390'),
            array('PHYS', '385'),
            array('PHYS', '384'),
            array('PHYS', '273'),
            array('BIOL', '208'),
        ),

        'Fall' => array(
            array('COMP', '465'),
            array('COMP', '442'),
            array('COMP', '444'),
            array('SOEN', '487'),
            array('COMP', '477'),
            array('COMP', '476'),
            array('THEO', '233'),
            array('THEO', '204'),
            array('HIST', '205'),
            array('HIST', '202'),
            array('FMST', '215'),
            array('FLIT', '240'),
            array('RELI', '312'),
            array('RELI', '214'),
            array('GEOG', '210'),
            array('ENCS', '283'),
            array('PHYS', '354'),
            array('PHYS', '252'),
            array('CHEM', '209'),
            array('BIOL', '206'),
            array('SOEN', '448'),
            array('SOEN', '431'),
            array('COMP', '444'),
            array('SOEN', '321'),
            array('MANA', '266'),
            array('MANA', '213'),
            array('LBCL', '204'),
            array('LBCL', '203'),
            array('LBCL', '202'),
            array('LBCL', '201'),
            array('HIST', '283'),
            array('RELI', '374'),
            array('RELI', '218'),
            array('POLI', '390'),
            array('PHYS', '385'),
            array('PHYS', '384'),
            array('PHYS', '273'),
            array('BIOL', '208'),
        ),
     ),
);

?>