<?php
$config['COURSE_LIST'] = array(
    array( 'COMP', '107', 'COMP SCI INDUS EXPERIENCE I'),
    array( 'COMP', '108', 'COMP INDUS EXPER REF LRNG I'),
    array( 'COMP', '201', 'INTRODUCTION TO COMPUTING'),
    array( 'COMP', '207', 'COMP SCI INDUS EXPERIENCE II'),
    array( 'COMP', '208', 'COMP INDUS EXPER REF LRNG II'),
    array( 'COMP', '218', 'FUNDAMENTALS OF PROGRAMMING'),
    array( 'COMP', '228', 'SYSTEM HARDWARE'),
    array( 'COMP', '232', 'MATH. FOR COMPUTER SCIENCE'),
    array( 'COMP', '233', 'PROB. & STATS. FOR COMP. SC.'),
    array( 'COMP', '248', 'OBJ-ORIENTED PROGRAMMING I'),
    array( 'COMP', '249', 'OBJ-ORIENTED PROGRAMMING II'),
    array( 'COMP', '326', 'COMPUTER ARCHITECTURE'),
    array( 'COMP', '335', 'INTRO/THEORETICAL COMP SCI'),
    array( 'COMP', '339', 'COMBINATORICS'),
    array( 'COMP', '345', 'ADVANCED PROGRAM DESIGN, C++'),
    array( 'COMP', '346', 'OPERATING SYSTEMS'),
    array( 'COMP', '348', 'PRIN./PROGRAMMING LANGUAGES'),
    array( 'COMP', '352', 'DATA STRUCTURES + ALGORITHMS'),
    array( 'COMP', '353', 'DATABASES'),
    array( 'COMP', '354', 'SOFTWARE ENGINEERING I'),
    array( 'COMP', '361', 'ELEMENTARY NUMERICAL METHODS'),
    array( 'COMP', '367', 'TECH./SYMBOLIC COMPUTATIONS'),
    array( 'COMP', '371', 'COMPUTER GRAPHICS'),
    array( 'COMP', '376', 'INTRO. TO GAME DEVELOPMENT'),
    array( 'COMP', '426', 'MULTICORE PROGRAMMING'),
    array( 'COMP', '428', 'PARALLEL PROGRAMMING'),
    array( 'COMP', '442', 'COMPILER DESIGN'),
    array( 'COMP', '445', 'DATA COMM + COMP NETWORKS'),
    array( 'COMP', '451', 'DATABASE DESIGN'),
    array( 'COMP', '465', 'DESIGN+ANALYSIS/ALGORITHMS'),
    array( 'COMP', '472', 'ARTIFICIAL INTELLIGENCE'),
    array( 'COMP', '473', 'PATTERN RECOGNITION'),
    array( 'COMP', '474', 'INTELLIGENT SYSTEMS'),
    array( 'COMP', '476', 'ADVANCED GAME DEVELOPMENT'),
    array( 'COMP', '477', 'ANIMATION FOR COMPUTER GAMES'),
    array( 'COMP', '478', 'IMAGE PROCESSING'),
    array( 'COMP', '479', 'INFO. RETRIEVAL & WEB SEARCH'),
    array( 'COMP', '490', 'COMPUTER SCIENCE PROJECT I'),
    array( 'COMP', '492', 'COMPUTER SCIENCE PROJECT II'),
    array( 'COMP', '495', 'HONOURS SEMINAR'),
    array( 'CWTC', '100', 'COOP WORK TERM 1 (COMP)'),
    array( 'CWTC', '101', 'REFLECTIVE LEARNING I'),
    array( 'CWTC', '200', 'COOP WORK TERM 2 (COMP)'),
    array( 'CWTC', '201', 'REFLECTIVE LEARNING II'),
    array( 'CWTC', '300', 'COOP WORK TERM 3 (COMP)'),
    array( 'CWTC', '301', 'REFLECTIVE LEARNING III'),
    array( 'CWTC', '400', 'COOP WORK TERM 4 (COMP)'),
    array( 'CWTC', '401', 'REFLECTIVE LEARNING IV'),
    array( 'CWTC', '450', 'COOP WORK TERM 5 (COMP)'),
    array( 'CWTC', '460', 'COOP WORK TERM 6 (COMP)'),
    array( 'SOEN', '228', 'SYSTEM HARDWARE'),
    array( 'SOEN', '287', 'WEB PROGRAMMING'),
    array( 'SOEN', '331', 'INTRO TO FML MTHDS FOR SOEN'),
    array( 'SOEN', '341', 'SOFTWARE PROCESS'),
    array( 'SOEN', '342', 'SW REQUIREMENTS + SPECS.'),
    array( 'SOEN', '343', 'S.W. ARCHITECURE & DESIGN I'),
    array( 'SOEN', '344', 'S.W. ARCHITECURE & DESIGN II'),
    array( 'SOEN', '345', 'S.W. TESTING, VERIF & QA'),
    array( 'SOEN', '357', 'USER INTERFACE DESIGN'),
    array( 'SOEN', '384', 'MGMT+QUALITY CTRL./SW DEV.'),
    array( 'SOEN', '385', 'CONTROL SYSTEMS+APPLICATIONS'),
    array( 'SOEN', '387', 'WEB-BASED ENTER. APP DESIGN'),
    array( 'SOEN', '390', 'SOFTWARE ENGR. TEAM PROJECT'),
    array( 'SOEN', '422', 'EMBEDDED SYSTEMS/SOFTWARE'),
    array( 'SOEN', '423', 'DISTRIBUTED SYSTEMS'),
    array( 'SOEN', '487', 'WEB SERVICES & APPLICATIONS'),
    array( 'SOEN', '490', 'CAPSTONE SW ENGR DESIGN PROJ'),
);

?>